# Generated by Django 5.1.3 on 2025-02-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='own_code',
            field=models.CharField(db_collation='utf8_bin', max_length=10, verbose_name='refferal_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(db_collation='utf8_bin', max_length=10, verbose_name='refferal_code'),
        ),
    ]
